### ISSUE TITLE
[MS2] Summary of Milestone 2 tasks

### ISSUE THREAD

**Issue by shlrley** [UBC-MDS/gradecalculatorr#1]
Tasks (individual)

- [x] - Create R repo (Checklist 1-3) @yukunzGIT
- [x] - Code of Conduct, DESCRIPTION, CONTRIBUTING (Checklist 4-6) @shlrley
- [x] - README.Rmd (Checklist 7) @CChCheChen

Tasks (everyone)
- [x] - Write R function documentation
